### ISSUE TITLE
Pretraining fails with a TypeError 

### ISSUE THREAD

**Issue by rohanchn** [mittagessen/kraken#495]
`pretrain` fails with the following error:

`TypeError: __init__() got an unexpected keyword argument 'pb_ignored_metrics'`

My command is: `ketos pretrain -B 16 -f binary -d cuda:0 -o models/pretrain --mask-width 4 --mask-probability 0.2 --num-negatives 3 all.arrow`

I commented out `pb_ignored_metrics` and now the training session is in progress.

https://github.com/mittagessen/kraken/blob/b2beb405a9e9c8f76c7fedd49e7e6b2e2e766ba7/kraken/ketos/pretrain.py#L275-L284

But I couldn't find anything on `pb_ignored_metrics`.

Could you please explain the problem?

**Comment by rohanchn** [comment]
After `--min-epochs==100`, the session ended like this: `Moving best model models/pretrain_0.mlmodel (inf) to models/pretrain_best.mlmodel` 

I have ~105K lines for this session.

This looks wierd.

**Comment by mittagessen** [comment]
It's fixed in main. Both were regressions introduced by the upgrade to lightning 2.0/the resultant progress bar refactoring.

**Comment by rohanchn** [comment]
Thanks! But I still can't understand why the model from the initial epoch was chosen as the best at the end of the training session. Which model should be better? Surely not the one from the initial epoch, right? The loss came down from 1.2 to 0.5 over 100 epochs.

**Comment by mittagessen** [comment]
No, the tracking of the best model is done in a class attribute that just never got updated when I got rid of the `validation_step_end` callback. If you've got the log laying around you can just look for the best validation loss. Otherwise, just take the last model. As far as we know the pretraining losses are only approximate indicators of pretraining quality.

**Comment by rohanchn** [comment]
Right, thanks! Yes, I keep logs.
