### ISSUE TITLE
"kraken get default" fails

### ISSUE THREAD

**Issue by rcrath** [mittagessen/kraken#9]
running 

>kraken get default

fails with

~~~
$ kraken get default
Retrieving model	⣽Traceback (most recent call last):
  File "/usr/bin/kraken", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.4/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 1053, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.4/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.4/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.4/site-packages/kraken/kraken.py", line 249, in get
    partial(spin, 'Retrieving model'))
  File "/usr/lib/python3.4/site-packages/kraken/repo.py", line 44, in get_model
    desc = json.loads(raw)
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
~~~

**Comment by mittagessen** [comment]
It's fixed in version 0.7.1 (pip install -U kraken). I should probably write some unit tests to catch regressions in python 3 support. 

I see that you are using python 3. I don't want to talk you out of it but the python 3 version does not support loading of the usual pyrnn.gz networks as they are serialized in a way that there is no hope of ever deserializing them on python 3. They can be converted on python 2 to the protobuf format which is loadable on both python 2 and 3 (happens automatically by default). As such it is more a nice gimmick than an actual feature, especially with the missing training support (I'm working on that).

**Comment by rcrath** [comment]
Still having problems.  I think it is probably python3 related, but other things on the system (manjaro (arch based)) need python 3 as the default.  Can I rerun pip install w/ python 2 as the environment?  Or run kraken as it is installed under python 2?  Sorry if this is a basic question.

**Comment by mittagessen** [comment]
First some general hints regarding python (2 and 3) software. Never, ever install stuff globally, i.e. as root. In contrast to most system programmers the python community as a whole does not seem to be able to build software with stable, backward-compatible APIs, instead relying on requirements files specifying certain versions of libraries. To always have a working system I recommend installing everything not from your distribution's sources into isolated [virtualenvs](https://virtualenv.pypa.io). This also allows installation without root privileges and it's easy to create and destroy them. 

If you got virtualenv (it may be in your distribution's sources) you can tell it to just use a python 2.7 interpreter for the environment using the -p switch. After that you proceed as usual.

**Comment by umang-singhal** [comment]
venv: Python 3.6
Kraken: 2.0.2.dev2(latest git)

running
> kraken get default

now fails with 
```python
$ kraken get default
Retrieving model .[1.3885] Found 0 models when querying for id 'default' 
Traceback (most recent call last):
  File "/home/umangsinghal/.local/share/virtualenvs/ocr-zrDUkC-9/bin/kraken", line 10, in <module>
    sys.exit(cli())
  File "/home/umangsinghal/.local/share/virtualenvs/ocr-zrDUkC-9/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/umangsinghal/.local/share/virtualenvs/ocr-zrDUkC-9/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/umangsinghal/.local/share/virtualenvs/ocr-zrDUkC-9/lib/python3.6/site-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/umangsinghal/.local/share/virtualenvs/ocr-zrDUkC-9/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/umangsinghal/.local/share/virtualenvs/ocr-zrDUkC-9/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/umangsinghal/.local/share/virtualenvs/ocr-zrDUkC-9/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/umangsinghal/.local/share/virtualenvs/ocr-zrDUkC-9/lib/python3.6/site-packages/kraken/kraken.py", line 445, in get
    partial(message, '.', nl=False))
  File "/home/umangsinghal/.local/share/virtualenvs/ocr-zrDUkC-9/lib/python3.6/site-packages/kraken/repo.py", line 117, in get_model
    raise KrakenRepoException('Found {} models when querying for id \'{}\''.format(resp['hits']['total'], model_id))
kraken.lib.exceptions.KrakenRepoException: Found 0 models when querying for id 'default'
```
Also, the latest git repo is broken. I updated the repo.py at line 116 for mismatch in number of arguments to print error message.

**Comment by mittagessen** [comment]
The new repository uses different persistent identifiers. Running `kraken get 10.5281/zenodo.2577813` should get you the latest english default model. The docs will be updated in the next few days.

**Comment by rcrath** [comment]
@mittagessen  it has been running from the arch AUR fine for a while now.  This can close I think. Thanks for your help on it.
